// This is the entire content of your new file: rosters.js

export const STAFF_NAMES = [
    "Fawas Hudawi", "Usman Darimi", "Abbas Anwari", "Sayid Habeebuallah faizy",
    "Rashad Hudawi", "Fayiz Hudawi", "Misfar Wafy", "Fayiz Nujoomi",
    "Farooq Hudawi", "Hafiz Hudawi", "Hamza Hudawi", "Anas Hudawi",
    "Jaleel Hudawi", "Shafeeq Hudawi", "Iqbal  Hudawi", "Shibil Hudawi",
    "Shuhaib Hudawi", "Abdurahman Hudawi", "Swalih Hudawi", "Gulam Sarwar Hudawi"
];

export const CLASS_NAMES = [
    "Class 1", "Class 2", "Class 3", "Class 4", "Class 5",
    "Class 6", "Class 7", "Class 8", "Class 9", "Class 10"
];

export const ATTENDANCE_STATUSES = ["Present", "Absent", "Late", "Excused"];

// Fill this object with your actual student names for each class
export const STUDENT_ROSTERS = {
    "Class 1": [
        "Student A1", "Student A2", "Student A3", "Student A4",
        "Muhammed Hishan VP",
        "Muhammed Shamil",
        "Muhammed Shifan Tn",
        "Muhammed Shazin K",
        "Muhammed Al Ameen P",
        "Sidhan C P",
        "Adnan Al Razeen M P",
        "Muhammed Rzhin K",
        "Muhammed Shihan P K",
        "Muhammed Nasfan E",
        "Muhammed Rihhin K",
        "Muhammed Rahin Pt",
        "Ssiman Ahhzhd E",
        "Mohammed Nihal. T",
        "Muhammed Rasin K P P",
        "Mohammed Jifan KP P",
        "Mohammed Jishin T M",
        "Sireseed Rasil T",
        "Muhammed Musthafa. Cp",
        "Muhammed Hanan. Cp",
        "Salman K",
        "Salman K",
        "Ahmed Rafid",
        "Muhammed Nadhi"
    ],
    "Class 2": [
        "Hathwib M",
        "Shifin Muhammed Kp",
        "Ahamed Zayan",
        "Mohamed Rayyan K",
        "Muhammed Swabeeh",
        "Muhammed Shihan C",
        "Muhammed Faris Pp",
        "Muhammed Aflah N",
        "Ijaz Ahmad K",
        "Amjad N K",
        "Muhammed Musawir K",
        "Muhammed Aarif V",
        "Muhammed Ashmil Pk",
        "Muhammed Farhan. Mp",
        "Muhammed Sinan V",
        "Abdulla Hafiz Mk",
        "Muhammed Nishan Cp",
        "Muhammed Shahil M",
        "Muhammed Mishal Nk",
        "Muhammed Swalih A",
        "Muhammed Shammas A",
        "Sahlu Zaman Cp",
        "Anshif M",
        "Salmanul Faris.M",
        "Rumaizan P T",
        "Mohammed Hadi M.C.",
        "Muhammed Shabeel.K",
        "Mohamed Swabeeh Pt",
        "Muhammed Ameen K",
        "Muhammed Musthafa E",
        "Muhammed Adnan N K",
        "Abu Bakr"
    ],
    "Class 3": [
        "Muhammed Rishel Vp",
        "Mohammed Sahadh Ct",
        "Mohammed Nabeel Pk",
        "Muhammed Farzeen N",
        "Muhammed Swabeeh K",
        "Muhammed Shibili.K",
        "Anshid.T",
        "Muhammed Shamil Vp",
        "Muhammad Rihan. P",
        "Muhammad Rashid K",
        "Thameem Aflah.A",
        "Rushaid.T",
        "Muhammad Faheem",
        "Muhammad Aflah Kp",
        "Muhammed Rabeeh T",
        "Muhammed Anshif N",
        "Muhammed Fadil M",
        "Muhammed Musthafa N",
        "Mohammed Siyan.V",
        "Sahad Muhammed Mv",
        "Muhammed Kaif. P",
        "Muhammed Ameen Kp",
        "Muhammed Salik P K",
        "Muhammed Mazin P",
        "Muhammed Rishal E",
        "Mohammed Hamdan. T",
        "Muhammad Adnan Kt",
        "Muhammad Salih",
        "Muhammad Faizan",
        "Fasalul Haq O",
        "Muhammed Shamil K",
        "M. T Ahmad Mujthaba"
    ],
    "Class 4": [
        "Abdullah Razi",
        "Mohammad Shamil Km",
        "Muhammed Milhan. T",
        "Mohammad Shifin K",
        "Muhammed Kp",
        "Shahin Hassan Ck",
        "Mohommed Shahsad P",
        "Muhammed Sinan T H",
        "Mohammed Sinan",
        "Rifan Unneen P K",
        "Muhammed Shamil C",
        "Muhammed Sinan Ck",
        "Ahammed Kabeer Kt",
        "Muhammed Nishan Ap",
        "Muhammed Sanub Tp",
        "Muhammed Nasmal",
        "Muhammad Basil K",
        "Nishad Km",
        "Muhammed Asjad O",
        "Saiful Azman C P",
        "Imran Uwaisi. K",
        "Muhammed Ismail",
        "Muhammed Suhail N",
        "Mohammed Anas C",
        "Muhammed Ajmal",
        "Muhammed Aflah",
        "Mohammed Hisham",
        "Muhammed Muhsin K",
        "Sufyan C",
        "Anas Kp",
        "Muhammed Sha. K",
        "Muhammed Dilshad T",
        "Hanan Ahmed. P",
        "Adhnan Mohammed. V",
        "Mohammed Rabeeh K",
        "Mohommed Sahal CK"
    ],
    "Class 5": [
        "Abdurahman T",
        "Rinshad C",
        "Misab N",
        "Muhammed Mikhdad T",
        "Sahad Kp",
        "Mohammed Ziyad V",
        "Muhammed Shibil C P",
        "Muhammed Risvan Tk",
        "Rayyan Muhammed O",
        "Shayal Mohammad",
        "Shibil V",
        "Ahadhal K",
        "Muhammad Husni A",
        "Mohammed Aseem K",
        "Muhammed Labeeb U",
        "Muhammed Musthafa",
        "Muhammed Sahal Vt",
        "Muhammed Hisham P.K",
        "Ahmad Ameen Pk",
        "Muhammed Hanan .P",
        "Yahqoob Ahammed V",
        "Ummer Shan Pk",
        "Muhammed Sawad C",
        "Adhil Muhammad K",
        "Rishal. C.M",
        "Riswan P",
        "Anas Ep",
        "Mohammed Nihal Kk",
        "Anzil K"
    ],
    "Class 6": [
        "Muhammed Nasih Nk",
        "Nasal Abdulla Pp",
        "Mohammed Jalal. Nk",
        "Mohammed Sinan T",
        "Muhammad Jalal",
        "Muhammed Faheem",
        "Muhammed Safwan",
        "Shinas Muhammed Pt",
        "Al Sabith P",
        "Muhammed Hisham Pp",
        "Hadi Sheril",
        "Muhammed Shamil P",
        "Hashim Farhan Kt",
        "Ishaque K",
        "Mohamed Rehan Km",
        "Muhammed Ashmil E",
        "Muhammed Rabeeh M",
        "Sanjid K",
        "Muhammed Afnan T",
        "Abdul Adhil M",
        "Muhammed Nihal. M",
        "Muhammed Rishan Kp",
        "Muhammed Yahya",
        "Muhammed Arshid A",
        "Ahmad Yaseen",
        "Yaseen Ka",
        "Muhammed Faheem P",
        "Muhammed Rabeeh K",
        "Shahal Kk"
    ],
    "Class 7": [
        "Shamil Aman A V",
        "Muhammad Hashir K",
        "Muhammed Shibili",
        "Muhammed Sinan Shah. Kp",
        "Hashim Aboobacker",
        "Mohammed Ismayil",
        "Muhammed Murshid C",
        "Muhammed Najvan P",
        "Mohamed Mikhdad N",
        "Shadhil Hathif",
        "Muhammed Sajid K",
        "Muhammed Akhnas",
        "Muhammed Rasal",
        "Muhammed Rashdhan",
        "Muhammed Adil Ck",
        "Muhammed Swalih V",
        "Muhammed Sahal C",
        "Muhammed Shanil M K",
        "Muhammed Favad Kp",
        "Mahjoob Shahdan Ct",
        "Muhammed Jasim K",
        "Muhammed Sabith"
    ],
    "Class 8": [
        "Muhammed Jalal",
        "Adil Muhammed Ck",
        "Muhammed Sinan Pt",
        "Muhammed Nihad K",
        "Arshad Kt",
        "Muhammed Afsal Pt",
        "Mohamed Yasin Ck",
        "Muhammed Hisam N",
        "Aseem Roshan Kp",
        "Muhamed Baheej Ka",
        "Muhammed Faris C",
        "Mohammed Al Sabith",
        "Muhammed Thajul Haqu N",
        "Mohammed Sahal P",
        "Afnan L",
        "Muhammed Shabeer",
        "Adil N",
        "Muhammed Sabith P",
        "Muhammed Hisham P",
        "Muhammed Favas P",
        "Jalaudheen Pk",
        "Muhammed Rishan Kk",
        "Muhammed Sinan E",
        "Muhammed Shanil P",
        "Farhan",
        "Faris"
    ],
    "Class 9": [
        "Muhammed Amjad Khan",
        "Muhammed Hashim",
        "Muhammed Shameel Kp",
        "Mohammed Suhail",
        "Muhammed Midilaj C K",
        "Ibrahim Badhusha",
        "Muhammed Javad",
        "Muhammed Suhail",
        "Muhammed Labeeb",
        "Muhammed Shamil",
        "Roshan",
        "Muhammed Hafis",
        "Mohammed Ameen K K",
        "Muhammed Najad",
        "Muhammed Anshid .K",
        "Muhammed Adnan",
        "Muhammed Nazal. P",
        "Mikdad",
        "Minhaj",
        "Muhammed Dilshad"
    ],
    "Class 10": [
        "Adil Muhammed",
        "Mohammed Salim",
        "Muhammed Rabeean",
        "Muhammed Safeer",
        "Mohammed Anas",
        "Muhammed Shibil",
        "Muhammed Midlaj",
        "Muhammed Thahir P",
        "Mohammed Husni",
        "Muzammil",
        "Muhammed Musthafa",
        "Muhammed Thwayyib",
        "Muhammed Rabeen",
        "Asheem Muhammed",
        "Muhammed Munawar",
        "Muhammed Abdullah",
        "Moosa Fayiz",
        "Mohammed Basil",
        "Mohammed Nishad",
        "Fawad",
        "Rinshad",
        "Muhammed Azhar",
        "Ashiq"
    ]
};